### rg.conf (file location set by RIPGREP_CONFIG_PATH)

###--colors=line:style:intense 
--colors=line:fg:172
--colors=column:fg:136 
--colors=match:fg:202 
--colors=match:style:bold  
--colors=path:style:intense 
--colors=path:fg:142 
--colors=path:style:underline
