#!/bin/bash

LAYOUT_PATH=~/.screenlayout/

LAYOUT=$(ls "$LAYOUT_PATH" | rofi -dmenu)

if [ -n "$LAYOUT" ]; then
    $LAYOUT_PATH$LAYOUT
    
    # restart i3 in-place preserving layout
    i3-msg restart

    feh --bg-fil ~/Documents/photos/snoopy-writing.jpg
fi
